=== baliking01/EIO1RQ_XMLGyak/XMLTaskEIO1RQ/XML_XSD/XMLSchemaeio1rq.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <!-- Egyszerű típusok kigyűjtése -->
  <xs:element name="irányító_szám" type="irszámTípus"/>
  <xs:element name="város" type="xs:string"/>
  <xs:element name="utca_házszám" type="utcaházTípus"/>
  <xs:element name="termék_név" type="xs:string"/>
  <xs:element name="mennyiség" type="mennyiségTípus"/>
  <xs:element name="leszállítva" type="xs:boolean"/>
  <xs:element name="rendelés_dátuma" type="xs:date"/>
  <xs:element name="tel_szám" type="telefonTípus"/>
  <xs:element name="email" type="emailTípus"/>
  <xs:element name="cégnév" type="xs:string"/>
  <xs:element name="beosztás" type="xs:string"/>
  <xs:element name="mikortól" type="xs:date"/>
  <xs:element name="név" type="xs:string"/>


  <!-- Egyszerű típusok definiálása -->
  <xs:simpleType name="irszámTípus">
    <xs:restriction base="xs:int">
        <xs:minInclusive value="1000" />
        <xs:maxInclusive value="9999" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="utcaházTípus">
    <xs:restriction base="xs:string">
        <xs:pattern value="([a-z A-Z]* \d+.( \d+\/\d+)?)" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="mennyiségTípus">
    <xs:restriction base="xs:int">
       <xs:minInclusive value="1" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="telefonTípus">
    <xs:restriction base="xs:string">
       <xs:pattern value="(\+36\ ?\d{1,2}\ ?\d{3}\ ?\d{4})" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="emailTípus">
    <xs:restriction base="xs:string">
       <xs:pattern value="([a-zA-Z0-9]*@[a-zA-Z]*.[a-zA-Z]*)" />
    </xs:restriction>
  </xs:simpleType>



  <!-- Komplex típusok definiálása-->
  <xs:complexType name="rendelésTípus">
    <xs:sequence>
      <xs:element ref="termék_név"/>
      <xs:element ref="mennyiség"/>
      <xs:element ref="leszállítva"/>
      <xs:element name="szállítási_hely">
        <xs:complexType>
          <xs:sequence>
            <xs:element ref="irányító_szám"/>
            <xs:element ref="város"/>
            <xs:element ref="utca_házszám"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="RENDELÉS_ID" type="xs:integer" use="required" />
    <xs:attribute name="RÉSZLEG_FK" type="xs:integer" use="required" />
  </xs:complexType>

  <xs:complexType name="rendelTípus">
    <xs:sequence>
      <xs:element ref="rendelés_dátuma"/>
    </xs:sequence>
    <xs:attribute name="RENDEL_ID" type="xs:integer" use="required" />
    <xs:attribute name="RENDELÉS_FK" type="xs:integer" use="required" />
    <xs:attribute name="MEGRENDELŐ_FK" type="xs:integer" use="required" />
  </xs:complexType>

  <xs:complexType name="megrendelőTípus">
    <xs:sequence>
      <xs:element ref="cégnév"/>
      <xs:element name="elérhetőség">
        <xs:complexType>
          <xs:sequence>
            <xs:element ref="tel_szám" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element ref="email"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="MEGRENDELŐ_ID" type="xs:integer" use="required" />
  </xs:complexType>

  <xs:complexType name="dolgozikTípus">
    <xs:sequence>
      <xs:element ref="beosztás"/>
    </xs:sequence>
    <xs:attribute name="DOLGOZIK_ID" type="xs:integer" use="required" />
    <xs:attribute name="RÉSZLEG_FK" type="xs:integer" use="required" />
    <xs:attribute name="DOLGOZÓ_FK" type="xs:integer" use="required" />
  </xs:complexType>

  <xs:complexType name="dolgozóTípus">
    <xs:sequence>
      <xs:element ref="név"/>
    </xs:sequence>
    <xs:attribute name="DOLGOZÓ_ID" type="xs:integer" use="required" />
  </xs:complexType>

  <xs:complexType name="vezetiTípus">
    <xs:sequence>
      <xs:element ref="mikortól"/>
    </xs:sequence>
    <xs:attribute name="VEZETI_ID" type="xs:integer" use="required" />
    <xs:attribute name="DOLGOZÓ_FK" type="xs:integer" use="required" />
    <xs:attribute name="RÉSZLEG_FK" type="xs:integer" use="required" />
  </xs:complexType>

  <xs:complexType name="részlegTípus">
    <xs:sequence>
      <xs:element ref="név"/>
    </xs:sequence>
    <xs:attribute name="RÉSZLEG_ID" type="xs:integer" use="required" />
  </xs:complexType>



  <!-- Dokumentum felépítése a gyökérleemtől -->
  <xs:element name="EIO1RQ_Logisztikai_Cég">
    <xs:complexType>
      <xs:sequence>
         <xs:element name="rendelés" type="rendelésTípus" minOccurs="0" maxOccurs="unbounded"/>
         <xs:element name="rendel" type="rendelTípus" minOccurs="0" maxOccurs="unbounded"/>
         <xs:element name="megrendelő" type="megrendelőTípus" minOccurs="0" maxOccurs="10"/>
         <xs:element name="dolgozik" type="dolgozikTípus" minOccurs="0" maxOccurs="unbounded"/>
         <xs:element name="dolgozó" type="dolgozóTípus" minOccurs="0" maxOccurs="unbounded"/>
         <xs:element name="vezeti" type="vezetiTípus" minOccurs="0" maxOccurs="unbounded"/>
         <xs:element name="részleg" type="részlegTípus" minOccurs="0" maxOccurs="20"/>
      </xs:sequence>
    </xs:complexType>



    <!-- Elsődleges kulcsok-->
    <xs:key name="rendelés_kulcs">
      <xs:selector xpath="rendelés"/>
      <xs:field xpath="@RENDELÉS_ID"/>
    </xs:key>

    <xs:key name="rendel_kulcs">
      <xs:selector xpath="rendel"/>
      <xs:field xpath="@RENDEL_ID"/>
    </xs:key>

    <xs:key name="megrendelő_kulcs">
      <xs:selector xpath="megrendelő"/>
      <xs:field xpath="@MEGRENDELŐ_ID"/>
    </xs:key>

    <xs:key name="dolgozik_kulcs">
      <xs:selector xpath="dolgozik"/>
      <xs:field xpath="@DOLGOZIK_ID"/>
    </xs:key>

    <xs:key name="dolgozó_kulcs">
      <xs:selector xpath="dolgozó"/>
      <xs:field xpath="@DOLGOZÓ_ID"/>
    </xs:key>

    <xs:key name="vezeti_kulcs">
      <xs:selector xpath="vezeti"/>
      <xs:field xpath="@VEZETI_ID"/>
    </xs:key>

    <xs:key name="részleg_kulcs">
      <xs:selector xpath="részleg"/>
      <xs:field xpath="@RÉSZLEG_ID"/>
    </xs:key>



    <!-- Idegen kulcsok-->
    <xs:keyref name="részleg_rendelés_kulcs" refer="részleg_kulcs">
      <xs:selector xpath="rendelés"/>
      <xs:field xpath="@részleg"/>
    </xs:keyref>

    <xs:keyref name="rendel_rendelés_kulcs" refer="rendelés_kulcs">
      <xs:selector xpath="rendel"/>
      <xs:field xpath="@rendelés"/>
    </xs:keyref>

    <xs:keyref name="rendel_megrendelő_kulcs" refer="megrendelő_kulcs">
      <xs:selector xpath="rendel"/>
      <xs:field xpath="@megrendelő"/>
    </xs:keyref>

    <xs:keyref name="dolgozik_részleg_kulcs" refer="részleg_kulcs">
      <xs:selector xpath="dolgozik"/>
      <xs:field xpath="@részleg"/>
    </xs:keyref>

    <xs:keyref name="dolgozik_dolgozó_kulcs" refer="dolgozó_kulcs">
      <xs:selector xpath="dolgozik"/>
      <xs:field xpath="@dolgozó"/>
    </xs:keyref>

    <xs:keyref name="vezeti_részleg_kulcs" refer="részleg_kulcs">
      <xs:selector xpath="vezeti"/>
      <xs:field xpath="@részleg"/>
    </xs:keyref>


    <!-- 1:1 kapcsolatok -->
    <xs:unique name="vezeti_dolgozó_egyegy">
        <xs:selector xpath="vezeti"/>
        <xs:field xpath="@dolgozó"/>
    </xs:unique>

  </xs:element>

</xs:schema>

=== baliking01/EIO1RQ_XMLGyak/XMLTaskEIO1RQ/DOMParseEIO1RQ/XMLeio1rq_Modified.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><EIO1RQ_Logisztikai_Cég xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="XMLSchemaeio1rq.xsd">

	<!-- Rendelés -->
	<rendelés RENDELÉS_ID="1" RÉSZLEG_FK="1">
		<termék_név>Ásványvíz</termék_név>
		<mennyiség>13</mennyiség>
		<leszállítva>true</leszállítva>
		<szállítási_hely>
			<irányító_szám>3519</irányító_szám>
			<város>Miskolc</város>
			<utca_házszám>Apat utca 12.</utca_házszám>
		</szállítási_hely>
	</rendelés>

	<rendelés RENDELÉS_ID="2" RÉSZLEG_FK="2">
		<termék_név>Hamburger pogácsa</termék_név>
		<mennyiség>20</mennyiség>
		<leszállítva>false</leszállítva>
		<szállítási_hely>
			<irányító_szám>6723</irányító_szám>
			<város>Szedeg</város>
			<utca_házszám>Eperjesi sor 2.</utca_házszám>
		</szállítási_hely>
	</rendelés>

	<rendelés RENDELÉS_ID="3" RÉSZLEG_FK="3">
		<termék_név>Sony WH-XB910N fejhallgató</termék_név>
		<mennyiség>8</mennyiség>
		<leszállítva>true</leszállítva>
		<szállítási_hely>
			<irányító_szám>9025</irányító_szám>
			<város>Győr</város>
			<utca_házszám>Akac utca 35.</utca_házszám>
		</szállítási_hely>
	</rendelés>

	<rendelés RENDELÉS_ID="4" RÉSZLEG_FK="2">
		<termék_név>Csirkemellfilé</termék_név>
		<mennyiség>20</mennyiség>
		<leszállítva>true</leszállítva>
		<szállítási_hely>
			<irányító_szám>7634</irányító_szám>
			<város>Pécs</város>
			<utca_házszám>Lankas utca 22.</utca_házszám>
		</szállítási_hely>
	</rendelés>

	<rendelés RENDELÉS_ID="5" RÉSZLEG_FK="1">
		<termék_név>Coca Cola Cherry 6x1.5L</termék_név>
		<mennyiség>17</mennyiség>
		<leszállítva>false</leszállítva>
		<szállítási_hely>
			<irányító_szám>4028</irányító_szám>
			<város>Debrecen</város>
			<utca_házszám>Abonyi utca 72.</utca_házszám>
		</szállítási_hely>
	</rendelés>

	<!-- Rendel -->
	<rendel MEGRENDELŐ_FK="1" RENDEL_ID="1" RENDELÉS_FK="1">
		<rendelés_dátuma>2023-01-17</rendelés_dátuma>
	</rendel>

	<rendel MEGRENDELŐ_FK="2" RENDEL_ID="2" RENDELÉS_FK="2">
		<rendelés_dátuma>2023-06-04</rendelés_dátuma>
	</rendel>
	
	<rendel MEGRENDELŐ_FK="3" RENDEL_ID="3" RENDELÉS_FK="3">
		<rendelés_dátuma>2023-08-23</rendelés_dátuma>
	</rendel>

	<rendel MEGRENDELŐ_FK="1" RENDEL_ID="4" RENDELÉS_FK="3">
		<rendelés_dátuma>2023-02-10</rendelés_dátuma>
	</rendel>

	<rendel MEGRENDELŐ_FK="3" RENDEL_ID="5" RENDELÉS_FK="3">
		<rendelés_dátuma>2023-12-05</rendelés_dátuma>
	</rendel>

	<!-- Megrendelő -->
	<megrendelő MEGRENDELŐ_ID="1">
		<cégnév>Fenyó és Társa Kft.</cégnév>
		<elérhetőség>
			<tel_szám>+3612045966</tel_szám>
			<email>info@tlx.hu</email>
		</elérhetőség>
	</megrendelő>

	<megrendelő MEGRENDELŐ_ID="2">
		<cégnév>Rothmayer Bt.</cégnév>
		<elérhetőség>rothmayerbt@gmail.comm</elérhetőség>
	</megrendelő>

	<megrendelő MEGRENDELŐ_ID="3">
		<cégnév>Horváth Uno Kft.</cégnév>
		<elérhetőség>
			<tel_szám>+36705469391</tel_szám>
			<email>horvathuno@gmail.com</email>
		</elérhetőség>
	</megrendelő>



	<!-- Dolgozik -->
	<dolgozik DOLGOZIK_ID="1" DOLGOZÓ_FK="1" RÉSZLEG_FK="1">
		<beosztás>Logisztikai menedzser</beosztás>
	</dolgozik>

	<dolgozik DOLGOZIK_ID="2" DOLGOZÓ_FK="2" RÉSZLEG_FK="1">
		<beosztás>Élelmiszer mérnök</beosztás>
	</dolgozik>

	<dolgozik DOLGOZIK_ID="3" DOLGOZÓ_FK="3" RÉSZLEG_FK="2">
		<beosztás>Targonca kezelő</beosztás>
	</dolgozik>

	<dolgozik DOLGOZIK_ID="4" DOLGOZÓ_FK="4" RÉSZLEG_FK="2">
		<beosztás>Villanyszerelő</beosztás>
	</dolgozik>

	<dolgozik DOLGOZIK_ID="5" DOLGOZÓ_FK="5" RÉSZLEG_FK="3">
		<beosztás>Informatikus</beosztás>
	</dolgozik>

	<dolgozik DOLGOZIK_ID="6" DOLGOZÓ_FK="6" RÉSZLEG_FK="3">
		<beosztás>Gazdasági tanácsadó</beosztás>
	</dolgozik>



	<!-- Dolgozó -->
	<dolgozó DOLGOZÓ_ID="1">
		<név>Kovács Béla</név>
	</dolgozó>

	<dolgozó DOLGOZÓ_ID="2">
		<név>Kiss János</név>
	</dolgozó>

	<dolgozó DOLGOZÓ_ID="3">
		<név>Eged Csanád</név>
	</dolgozó>

	<dolgozó DOLGOZÓ_ID="4">
		<név>Kun Tamás</név>
	</dolgozó>

	<dolgozó DOLGOZÓ_ID="5">
		<név>Cziglédi Bálint</név>
	</dolgozó>

	<dolgozó DOLGOZÓ_ID="6">
		<név>Tóth Sándor</név>
	</dolgozó>



	<!-- Vezeti -->
	<vezeti DOLGOZÓ_FK="5" RÉSZLEG_FK="1" VEZETI_ID="1">
		<mikortól>2023-12-05</mikortól>
	</vezeti>

	<vezeti DOLGOZÓ_FK="3" RÉSZLEG_FK="2" VEZETI_ID="2">
		<mikortól>2019-04-15</mikortól>
	</vezeti>

	<vezeti DOLGOZÓ_FK="6" RÉSZLEG_FK="3" VEZETI_ID="3">
		<mikortól>2020-09-07</mikortól>
	</vezeti>



	<!-- Részleg -->
	<részleg RÉSZLEG_ID="1">
		<név>Élelmiszer</név>
	</részleg>

	<részleg RÉSZLEG_ID="2">
		<név>Ital</név>
	</részleg>
	
	<részleg RÉSZLEG_ID="3">
		<név>Informatika</név>
	</részleg>

</EIO1RQ_Logisztikai_Cég>

=== baliking01/EIO1RQ_XMLGyak/XMLTaskEIO1RQ/XML_XSD/XMLeio1rq.xml
<?xml version="1.0" encoding="UTF-8"?>

<EIO1RQ_Logisztikai_Cég xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:noNamespaceSchemaLocation="XMLSchemaeio1rq.xsd">

	<!-- Rendelés -->
	<rendelés RENDELÉS_ID="1" RÉSZLEG_FK="1">
		<termék_név>Ásványvíz</termék_név>
		<mennyiség>13</mennyiség>
		<leszállítva>true</leszállítva>
		<szállítási_hely>
			<irányító_szám>3519</irányító_szám>
			<város>Miskolc</város>
			<utca_házszám>Apat utca 12.</utca_házszám>
		</szállítási_hely>
	</rendelés>

	<rendelés RENDELÉS_ID="2" RÉSZLEG_FK="2">
		<termék_név>Hamburger pogácsa</termék_név>
		<mennyiség>20</mennyiség>
		<leszállítva>false</leszállítva>
		<szállítási_hely>
			<irányító_szám>6723</irányító_szám>
			<város>Szedeg</város>
			<utca_házszám>Eperjesi sor 2.</utca_házszám>
		</szállítási_hely>
	</rendelés>

	<rendelés RENDELÉS_ID="3" RÉSZLEG_FK="3">
		<termék_név>Sony WH-XB910N fejhallgató</termék_név>
		<mennyiség>8</mennyiség>
		<leszállítva>true</leszállítva>
		<szállítási_hely>
			<irányító_szám>9025</irányító_szám>
			<város>Győr</város>
			<utca_házszám>Akac utca 35.</utca_házszám>
		</szállítási_hely>
	</rendelés>



	<!-- Rendel -->
	<rendel RENDEL_ID="1" RENDELÉS_FK="1" MEGRENDELŐ_FK="1">
		<rendelés_dátuma>2023-01-17</rendelés_dátuma>
	</rendel>

	<rendel RENDEL_ID="2" RENDELÉS_FK="2" MEGRENDELŐ_FK="2">
		<rendelés_dátuma>2023-06-04</rendelés_dátuma>
	</rendel>
	
	<rendel RENDEL_ID="3" RENDELÉS_FK="3" MEGRENDELŐ_FK="3">
		<rendelés_dátuma>2023-08-23</rendelés_dátuma>
	</rendel>



	<!-- Megrendelő -->
	<megrendelő MEGRENDELŐ_ID="1">
		<cégnév>Fenyó és Társa Kft.</cégnév>
		<elérhetőség>
			<tel_szám>+3612045966</tel_szám>
			<email>info@tlx.hu</email>
		</elérhetőség>
	</megrendelő>

	<megrendelő MEGRENDELŐ_ID="2">
		<cégnév>Rothmayer Bt.</cégnév>
		<elérhetőség>
			<tel_szám>+3633413665</tel_szám>
			<email>rothmayer1@gmail.com</email>
		</elérhetőség>
	</megrendelő>

	<megrendelő MEGRENDELŐ_ID="3">
		<cégnév>Horváth Uno Kft.</cégnév>
		<elérhetőség>
			<tel_szám>+36705469391</tel_szám>
			<email>horvathuno@gmail.com</email>
		</elérhetőség>
	</megrendelő>



	<!-- Dolgozik -->
	<dolgozik DOLGOZIK_ID="1" RÉSZLEG_FK="1" DOLGOZÓ_FK="1">
		<beosztás>Logisztikai menedzser</beosztás>
	</dolgozik>

	<dolgozik DOLGOZIK_ID="2" RÉSZLEG_FK="1" DOLGOZÓ_FK="2">
		<beosztás>Élelmiszer mérnök</beosztás>
	</dolgozik>

	<dolgozik DOLGOZIK_ID="3" RÉSZLEG_FK="2" DOLGOZÓ_FK="3">
		<beosztás>Targonca kezelő</beosztás>
	</dolgozik>

	<dolgozik DOLGOZIK_ID="4" RÉSZLEG_FK="2" DOLGOZÓ_FK="4">
		<beosztás>Villanyszerelő</beosztás>
	</dolgozik>

	<dolgozik DOLGOZIK_ID="5" RÉSZLEG_FK="3" DOLGOZÓ_FK="5">
		<beosztás>Informatikus</beosztás>
	</dolgozik>

	<dolgozik DOLGOZIK_ID="6" RÉSZLEG_FK="3" DOLGOZÓ_FK="6">
		<beosztás>Gazdasági tanácsadó</beosztás>
	</dolgozik>



	<!-- Dolgozó -->
	<dolgozó DOLGOZÓ_ID="1">
		<név>Kovács Béla</név>
	</dolgozó>

	<dolgozó DOLGOZÓ_ID="2">
		<név>Kiss János</név>
	</dolgozó>

	<dolgozó DOLGOZÓ_ID="3">
		<név>Eged Csanád</név>
	</dolgozó>

	<dolgozó DOLGOZÓ_ID="4">
		<név>Kun Tamás</név>
	</dolgozó>

	<dolgozó DOLGOZÓ_ID="5">
		<név>Jámbor Andrea</név>
	</dolgozó>

	<dolgozó DOLGOZÓ_ID="6">
		<név>Tóth Sándor</név>
	</dolgozó>



	<!-- Vezeti -->
	<vezeti VEZETI_ID="1" RÉSZLEG_FK="1" DOLGOZÓ_FK="1">
		<mikortól>2017-01-01</mikortól>
	</vezeti>

	<vezeti VEZETI_ID="2" RÉSZLEG_FK="2" DOLGOZÓ_FK="3">
		<mikortól>2019-04-15</mikortól>
	</vezeti>

	<vezeti VEZETI_ID="3" RÉSZLEG_FK="3" DOLGOZÓ_FK="6">
		<mikortól>2020-09-07</mikortól>
	</vezeti>



	<!-- Részleg -->
	<részleg RÉSZLEG_ID="1">
		<név>Élelmiszer</név>
	</részleg>

	<részleg RÉSZLEG_ID="2">
		<név>Ital</név>
	</részleg>
	
	<részleg RÉSZLEG_ID="3">
		<név>Informatika</név>
	</részleg>

</EIO1RQ_Logisztikai_Cég>
